// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"account-service/internal/biz"
	"account-service/internal/conf"
	"account-service/internal/data"
	"account-service/internal/server"
	"account-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, jwt *conf.JWT, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	conn := data.NewRedis(confData)
	syncProducer := data.NewKafka(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db, conn, syncProducer)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, jwt, logger)
	accountService := service.NewAccountService(userUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, jwt, accountService, logger)
	grpcServer := server.NewGRPCServer(confServer, accountService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
