// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"week04/code/internal/apiserver/biz"
	"week04/code/internal/apiserver/data"
	"week04/code/internal/apiserver/server"
	"week04/code/internal/apiserver/service"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	dataData, cleanup, err := data.NewData()
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(greeterService)
	app, err := NewApp(grpcServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}
